version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./backend/db:/docker-entrypoint-initdb.d  # Auto-runs SQL files
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend