name: Test Pipeline
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd backend && npm install && npm test
      - run: cd frontend && npm install && npm test